### ISSUE TITLE
Dosya Dersinden Not Egzersizi

### ISSUE THREAD

**Issue by zehranrgi** [mustafamuratcoskun/Sifirdan-Ileri-Seviyeye-Python-Programlama#17]
![Capture](https://user-images.githubusercontent.com/70450368/93747485-72d4c380-fbff-11ea-815a-b5d310a48c31.JPG)

Ekte belirttiğim hatadan dolayı program devam etmiyor? Bakabilir misiniz? .

**Comment by Zaf4** [comment]
harf variable ını henüz bir değere assign etmeden önce kullanmaya çalışmışsın.
methodun için aldığın parametre ismiyle return ettiğin isim aynıysa da derleme sırasında hata veriyor.

>>>def func(harf):
....
>>>    return harf

yerine

>>> def func(harf):
>>>    harf1 = harf
>>>    return harf1

deneyebilirsin.

Ama kodunu koymadağının için sorunun kaynağı başka bir şey mi bilemiyorum.

**Comment by zehranrgi** [comment]
Teşekkür ederim..
