### ISSUE TITLE
Döngüler>> Break and Continue

### ISSUE THREAD

**Issue by zehranrgi** [mustafamuratcoskun/Sifirdan-Ileri-Seviyeye-Python-Programlama#22]
"""
i = 0 # Bu kodda Sonsuz döngü olayı neden oluşur ? Bu kodu çalıştırmayalım.

# Eğer çalıştırırsak sonsuz döngüyü "Kernel" sekmesinde 

while (i < 10):
    
    if (i == 2):
        continue
        
    print(i)
    i += 1
""""
Bu Dosya yolu içerisinde yer alan ders notunda herhangi bir sonsuz döngüye girme yok. ( PyCharm ver Jupiter üzerinden denedim hocam.
Saygılar.

**Comment by ymucahit** [comment]
Merhaba,

Aslında kodu biraz değiştirirsek sonsuz döngüye girdiğini daha rahat görebilirsin. continue ifadesi döngü kontrol ifadesine geri döndürür. i değişkenini tekrar arttırmadığınız için i her zaman 2'de kalacaktır. Zannedersem ekrana birşey bastırılmadığı için sonsuz döngüye girmediği düşüncesine vardın. Aşağıdaki kodda print'i yukarıya aldım daha rahat anlaşılması için. 0,1 ve 2'den sonra hep 2'yi bastıracaktır. 

```python
while (i < 10):
    print(i)
    if (i == 2):
        continue
    i += 1```

**Comment by ForeverTheHuman** [comment]
Çünkü i 2'ye eşit olduğunda döngü başa dönüyor ve i'nin 10'dan küçük olma durumunu kontrol ediyor. 2<10 sonucuyla karışılaşıldığı için döngü devam ediyor ve yeniden if koşulu kontrol ediliyor. Yine i, 2'ye eşit olduğu için döngünün başına dönüyor ve sonsuza kadar bu durum devam ediyor.

**Comment by ForeverTheHuman** [comment]
Kodunuzu şu şekilde düzenlersek döngünün sonuna kadar gittiğini ve i'nin 10'a eşit olduğunda döngünün sona erdiğini yani sonsuz döngüye girilmediğini görebileceksiniz. 

```python
i=0
while(i<10):
    print(i)
    i+=1
    if(i==2):
        continue
```

**Comment by zehranrgi** [comment]
Anladım, teşekkür ederim hızlı yanıtlarınız için :)

**Comment by lemreaskin** [comment]
Rica ederim, iyi çalışmalar dilerim.
