### ISSUE TITLE
boyle bir hata verdi ne yapa bilirim?

### ISSUE THREAD

**Issue by 3lvnvrzl** [mustafamuratcoskun/Sifirdan-Ileri-Seviyeye-Python-Programlama#26]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined
>>>

**Comment by lemreaskin** [comment]
Kodunda "python" isimli değişkenin tanımlanmadığını söylüyor. Kodu paylaşabilirsen daha çok yardım edebiliriz.

**Comment by 3lvnvrzl** [comment]
a = int(input("a:"))
b = int(input("b:"))
c = int(input("c:"))

delta = b ** 2 - 4 * a *c

x1 = (-b - delta ** 0.5) / (2 * a)
x2 =(-b + delta ** 0.5) / (2 * a)

print("Birinci Kök: {}\nİkinci Kök: {}\n".format(x1,x2))

**Comment by lemreaskin** [comment]
Kodda herhangi bir sorun bulunduğunu sanmıyorum.

**Comment by 3lvnvrzl** [comment]
<img width="997" alt="Ekran Resmi 2021-05-26 12 53 40" src="https://user-images.githubusercontent.com/84839170/119631947-6dc8b380-be21-11eb-94bc-4ee1a3a9d772.png">

**Comment by lemreaskin** [comment]
Sanırım sorunu anladım. Görünen o ki kodu konsol üzerinden çalıştırmaya çalışıyorsunuz ve dosya adınının ya da dosya yolunun başına "python" yazıyorsunuz. Ancak Python'a ait yorumlayıcı zaten konsol üzerinde çalıştığı için, kodunuza ait olan dosyayı konsol üzerinde Python yorumlayıcısıyla çalıştırmak istediğinizde, kullanıldığınız "python" anahtar kelimesini yorumlayıcı değişken olarak algılıyor ve bu değişkenin tanımlı olmadığını söylüyor.

**Comment by lemreaskin** [comment]
Alt tarafta bulunan konsola tıklayın, exit() yazın ve enterlayın. Sonra kodunuzu tekrar çalıştırmayı deneyin.

**Comment by 3lvnvrzl** [comment]
Çok teşekkür ederim sorun çözüldü

**Comment by lemreaskin** [comment]
Rica ederim. Konuyu kapatabilirsiniz çok iyi olur.

**Comment by 3lvnvrzl** [comment]
iyi aksam hocam boyle bir sorun olustu nasil duzelte bilirim?
![Uploading Ekran Resmi 2021-10-11 00.10.37.png…]()

**Comment by 3lvnvrzl** [comment]
hocam iyi aksam bi sorun olustu dediginiz gibi calismiyor

**Comment by 3lvnvrzl** [comment]
<img width="599" alt="Ekran Resmi 2021-10-11 00 10 37" src="https://user-images.githubusercontent.com/84839170/136713110-fb8a1536-e30a-4c9b-8115-6c30acd58d47.png">

**Comment by 3lvnvrzl** [comment]
<img width="619" alt="Ekran Resmi 2021-10-11 00 12 51" src="https://user-images.githubusercontent.com/84839170/136713135-3c53064c-f671-4af4-a8c6-330684dcd866.png">
