### ISSUE TITLE
Araya böyle birşey karışmış

### ISSUE THREAD

**Issue by ozkansen** [mustafamuratcoskun/Sifirdan-Ileri-Seviyeye-Python-Programlama#3]
...

**Comment by sarcasticterror** [comment]
wtf bu ne?

**Comment by ozkansen** [comment]
Tüm dosyaları listelerken dikkat etmek lazım, özel dosyalarda listeleniyor.

**Comment by yuceltoluyag** [comment]
nice yaprak.php hocam

**Comment by sweg616** [comment]
ohaaa bu ne abi hahah

**Comment by aybasaran10** [comment]
bence hocaya ozel mesaj olarak gondermelisiniz burda herkes goruyor.

**Comment by ozkansen** [comment]
👍👍

**Comment by omertunaa** [comment]
hahahah fsdjkfjsdkfasd

Mustafa Murat Coşkun <notifications@github.com>, 8 Eki 2019 Sal, 16:54
tarihinde şunu yazdı:

**Comment by omertunaa** [comment]
kusura bakmayın hocam şaşırdım biraz

Ömer Tuna <celebrimbortr@gmail.com>, 24 Eki 2019 Per, 21:56 tarihinde şunu
yazdı:

**Comment by omertunaa** [comment]
iyi fark etmişler

Ömer Tuna <celebrimbortr@gmail.com>, 24 Eki 2019 Per, 21:57 tarihinde şunu
yazdı:
