### ISSUE TITLE
Kodlama egzersizi-temel python objeleri ve yapıları bölümünde hata alıyorum

### ISSUE THREAD

**Issue by Adothb** [mustafamuratcoskun/Sifirdan-Ileri-Seviyeye-Python-Programlama#46]
print("Oyuncu Kaydetme Programı")

ad = input("Oyuncunun Adı")
Soyad =input("Oyuncunun Soyadı")
takım =input("Oyuncunun Takımı")

bilgiler[ad,soyad,takım]

print("Bilgiler Kaydediliyor...")

print("Oyuncunun Adı: {}\nOyuncunun Soyadı: {}\n Oyuncunun Takımı: {}\n".format(bilgiler[0],bilgiler[1],bilgiler[2]))

print("Bilgiler Kaydedildi.")

NameError: name 'bilgiler' is not defined

**Comment by lemreaskin** [comment]
Hocam 'bilgiler = [ad,soyad,takım]' yapmalısınız

**Comment by Adothb** [comment]
Çok teşekkür ederim iyi günler.


Windows için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: ***@***.***>
Gönderilme: 31 Ocak 2023 Salı 18:44
Kime: ***@***.***>
Bilgi: ***@***.***>; ***@***.***>
Konu: Re: [mustafamuratcoskun/Sifirdan-Ileri-Seviyeye-Python-Programlama] Kodlama egzersizi-temel python objeleri ve yapıları bölümünde hata alıyorum (Issue #46)


Hocam 'bilgiler = [ad,soyad,takım]' yapmalısınız

**Comment by lemreaskin** [comment]
Rica ederim. Sorun çözüldüyse konuyu "close" konuma getirebilirseniz çok iyi olur.
